on: push
name: Build and Deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.68.3'
    - name: Install
      run: npm install
    - name: Build
      run: npm run build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
    - name: Upload to S3
      if: github.ref == 'refs/heads/master'
      run: aws s3 sync ./public/ s3://www.gauntface.com/ --delete --acl public-read
    - name: Set Caching for everything to 24 hours
      if: github.ref == 'refs/heads/master'
      run: |
        aws s3 cp \
        s3://www.gauntface.com/ s3://www.gauntface.com/ \
        --metadata-directive REPLACE \
        --cache-control 'max-age=86400' \
        --exclude="*" \
        --include="*.html" \
        --include="*.xml" \
        --include="*.json" \
        --include="*.svg" \
        --acl public-read \
        --recursive
    - name: Set Caching for images to 360 days
      if: github.ref == 'refs/heads/master'
      run: |
        aws s3 cp \
        s3://www.gauntface.com/ s3://www.gauntface.com/ \
        --metadata-directive REPLACE \
        --cache-control 'max-age=31104000' \
        --exclude="*" \
        --include="*.css" \
        --include="*.js" \
        --include="*.png" \
        --include="*.jpg" \
        --include="*.jpeg" \
        --include="*.gif" \
        --include="*.webp" \
        --acl public-read \
        --recursive
    - name: Invalidate cloudfont
      if: github.ref == 'refs/heads/master'
      run: |
        aws cloudfront create-invalidation \
        --distribution-id E2XJO1NK2D7PWE \
        --paths "/*"