on: push
name: Build and Deploy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.62.2'
    - name: Install
      run: npm install
    - name: Build
      run: npm run build
  deploy:
    name: Deploy
    needs: build
    if: github.event_name == 'push' && github.ref == 'master'
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
    - name: Upload to S3
      run: aws s3 sync ./public/ s3://www.gauntface.com/ --delete